site_name: Railway Routing API Documentation
site_description: Railway Routing API
#site_favicon: https://graphhopper.com/favicon.ico
repo_url: https://github.com/geofabrik/railway-routing-api/
docs_dir: src
nav:
- Overview: index.md
- API parts:
  - Routing API: routing.md
#  - Route Optimization API: route-optimization.md  
#  - Geocoding API: geocoding.md
  - Map Matching API: map-matching.md
#  - Isochrone API: isochrone.md
#  - Matrix API: matrix.md
- Attribution: attribution.md
- Vehicles: supported-vehicle-profiles.md
#- FAQ: FAQ.md
extra_css: 
  - css/white_background.css
#extra_javascript:
#  - js/custom.js
# almost all other themes use Google Fonts
theme:
  name: mkdocs
  custom_dir: custom_theme
